[[profile]]
name = "laptop"
exec = ["~/dotfiles/.scripts/modes/modes/laptop.sh"]

[[profile.output]]
enable = true
search = ["m=0x403D", "s=", "v=Lenovo Group Limited"]
mode = "1920x1200@60.026Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
exec = ["swayws range --numeric 1 10 $SHIKANE_OUTPUT_NAME"]

[[profile]]
name = "docked"
exec = ["~/dotfiles/.scripts/modes/modes/docked.sh"]

[[profile.output]]
enable = false
search = ["m=0x403D", "s=", "v=Lenovo Group Limited"]

[[profile.output]]
enable = true
search = ["m=DELL P2417H", "s=CW6Y789D298B", "v=Dell Inc."]
mode = "1920x1080@60Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
exec = ["swayws range --numeric 1 5 $SHIKANE_OUTPUT_NAME"]

[[profile.output]]
enable = true
search = ["m=DELL P2417H", "s=CW6Y789D29GB", "v=Dell Inc."]
mode = "1920x1080@60Hz"
position = "1920,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
exec = ["swayws range --numeric 6 10 $SHIKANE_OUTPUT_NAME"]

[[profile]]
name = "present"

[[profile.output]]
enable = true
search = ["m=0x403D", "s=", "v=Lenovo Group Limited"]
mode = "1920x1080@60Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=SyncMaster", "s=H1AK500000", "v=Samsung Electric Company"]
mode = "1920x1080@30Hz"
position = "1920,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
exec = [
    "killall wl-present",
    "rm -f /run/user/1000/pipectl.1000.wl-present.pipe",
    "wl-present mirror eDP-1 --fullscreen-output $SHIKANE_OUTPUT_NAME --fullscreen"
]

