timeout = 3

[[profile]]
name = "laptop"
exec = [
  "notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""
]

[[profile.output]]
enable = true
search = ["m=0x403D", "s=", "v=Lenovo Group Limited"]
mode = "1920x1200@60.026Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
exec = [
  "sleep 5",
  "swayws range --numeric 1 10 $SHIKANE_OUTPUT_NAME",
  "swaybg -o $SHIKANE_OUTPUT_NAME -i /home/gary/Pictures/left.jpg -m fill &"
]

[[profile]]
name = "docked"
exec = [
  "notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""
]

[[profile.output]]
enable = false
search = ["m=0x403D", "s=", "v=Lenovo Group Limited"]

[[profile.output]]
enable = true
search = ["m=DELL P2417H", "s=CW6Y789D298B", "v=Dell Inc."]
mode = "1920x1080@60Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
exec = [
  "sleep 5",
  "swayws range --numeric 1 5 $SHIKANE_OUTPUT_NAME",
  "swaybg -o $SHIKANE_OUTPUT_NAME -i /home/gary/Pictures/left.jpg -m fill &"
]

[[profile.output]]
enable = true
search = ["m=DELL P2417H", "s=CW6Y789D29GB", "v=Dell Inc."]
mode = "1920x1080@60Hz"
position = "1920,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
exec = [
  "sleep 5",
  "swayws range --numeric 6 10 $SHIKANE_OUTPUT_NAME",
  "swaybg -o $SHIKANE_OUTPUT_NAME -i /home/gary/Pictures/right.jpg -m fill &"
]

[[profile]]
name = "present"
exec = [
  "notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""
]

[[profile.output]]
enable = true
search = ["m=0x403D", "s=", "v=Lenovo Group Limited"]
mode = "1920x1080@60Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=SyncMaster", "s=H1AK500000", "v=Samsung Electric Company"]
mode = "1920x1080@30Hz"
position = "1920,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
exec = [
  "killall wl-present",
  "rm -f /run/user/1000/pipectl.1000.wl-present.pipe",
  "wl-present mirror eDP-1 --fullscreen-output $SHIKANE_OUTPUT_NAME --fullscreen"
]

[[profile]]
name = "ecurie"
exec = [
  "notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""
]

[[profile.output]]
enable = true
search = ["m=0x403D", "s=", "v=Lenovo Group Limited"]
mode = "1920x1080@60.026Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=Beyond TV", "s=0x00010000", "v=XXX"]
mode = "1920x1080@30Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
# exec = [
#     "killall wl-present",
#     "rm -f /run/user/1000/pipectl.1000.wl-present.pipe",
#     "wl-present mirror eDP-1 --fullscreen-output $SHIKANE_OUTPUT_NAME --fullscreen"
# ]

[[profile]]
name = "docked-home"
exec = [
  "notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""
]

[[profile.output]]
enable = true
search = ["m=DELL S2725QS", "s=FVWF364", "v=Dell Inc."]
mode = "3840x2160@60Hz"
position = "0,0"
scale = 1.25
transform = "normal"
adaptive_sync = false
exec = [
  "sleep 5",
  "swayws range --numeric 1 5 $SHIKANE_OUTPUT_NAME",
  "swaybg -o $SHIKANE_OUTPUT_NAME -i /home/gary/Pictures/left.jpg -m fill &"
]

[[profile.output]]
enable = false
search = ["m=0x403D", "s=", "v=Lenovo Group Limited"]

[[profile.output]]
enable = true
search = ["m=DELL S2725QS", "s=JYPF364", "v=Dell Inc."]
mode = "3840x2160@60Hz"
position = "3072,0"
scale = 1.25
transform = "normal"
adaptive_sync = false
exec = [
  "sleep 5",
  "swayws range --numeric 6 10 $SHIKANE_OUTPUT_NAME",
  "swaybg -o $SHIKANE_OUTPUT_NAME -i /home/gary/Pictures/right.jpg -m fill &"
]
