[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#928374"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#3c3836"
yellow = "#b57614"

[colors.normal]
black = "#fbf1c7"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#7c6f64"
yellow = "#d79921"

[colors.primary]
background = "#fbf1c7"
foreground = "#3c3836"

[font]
size = 10.5

[font.normal]
family = "Bitstream Vera Sans Mono"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "PageUp"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "PageDown"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Alt"

[window]
decorations = "none"

[window.padding]
x = 2
y = 2
