alias reload-xresources="xrdb ~/.Xresources"
alias xopen="gio open"
alias mv='mv -i'
alias :q="exit"
alias calc="loffice --calc"
alias jp="jupyter-notebook"
alias fd="fd -H"
alias i3c="vim ~/.config/i3/config"
alias m="make"
alias wtr="curl 'http://wttr.in/lausanne?lang=fr'"
alias cmake="cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1"
alias vihosts="sudo vim /etc/hosts"

alias update-nnn-plugs="curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh"
alias n="nnn -e -P p"
